name : firstci-cd
on : push 
jobs: 
    firstjob: 
            runs-on : ubuntu-latest
            steps: 
              -name: first step
            run: echo "learn properly"
              
            -name: list file
     run: ls
